/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    categories: Category;
    posts: Post;
    pages: Page;
    'faq-categories': FaqCategory;
    integrations: Integration;
    'custom-collection-definitions': CustomCollectionDefinition;
    'custom-collection-entries': CustomCollectionEntry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'faq-categories': FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'custom-collection-definitions': CustomCollectionDefinitionsSelect<false> | CustomCollectionDefinitionsSelect<true>;
    'custom-collection-entries': CustomCollectionEntriesSelect<false> | CustomCollectionEntriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pl' | 'en' | 'de') | ('pl' | 'en' | 'de')[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    'page-type-collections': PageTypeCollection;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'page-type-collections': PageTypeCollectionsSelect<false> | PageTypeCollectionsSelect<true>;
  };
  locale: 'pl' | 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL slug for /news-post/[slug]
   */
  slug: string;
  shortDescription: string;
  featuredImage: number | Media;
  publishedAt: string;
  readTimeMinutes: number;
  categories?: (number | Category)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Settings for FAQ, Integrations, and News pages. One document per page type. Use slug for custom paths.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Klucz typu strony – musi być identyczny z polem "Page type key" w Globals → Page Type Collections (np. faq, integrations, news). Nowe typy dodaj najpierw w Page Type Collections.
   */
  pageType: string;
  /**
   * Opcjonalnie: powiąż tę stronę z konkretnym Wpisem danych (Data Entry).
   */
  dataEntry?: number | { id: number } | null;
  /**
   * Custom URL path (e.g. "pricing", "about"). If empty, path is determined by page type (faq, integrations, news).
   */
  slug?: string | null;
  title: string;
  shortDescription: string;
  /**
   * Content blocks for this page (e.g. hero, text, CTA). Used for custom pages like /pricing, /about.
   */
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            title: string;
            buttonLabel: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FAQ categories. Each category has a name, short description and many Q&A items.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories".
 */
export interface FaqCategory {
  id: number;
  name: string;
  shortDescription?: string | null;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Integration entries for /integrations page. Each has mini logo, company name, short description.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  shortDescription: string;
  logo: number | Media;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Definicje własnych kolekcji danych (np. Cennik, Cenniki). Tutaj nazywasz kolekcję i dodajesz pola (nazwa, typ). Później w Page Type Collections wybierasz tę kolekcję i dodajesz wpisy w Custom Collection Entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-collection-definitions".
 */
export interface CustomCollectionDefinition {
  id: number;
  /**
   * Czytelna nazwa, np. "Cennik", "PricesList" (używana w panelu).
   */
  name: string;
  /**
   * Unikalny identyfikator bez spacji (np. prices-list, cennik). Używany jako pageType w Pages – wpisz ten sam klucz w "Page type key" w Page Type Collections.
   */
  slug: string;
  /**
   * Klucz pola (z listy poniżej), które ma być wyświetlane jako tytuł w liście wpisów. Zostaw puste, jeśli nie dotyczy.
   */
  useAsTitle?: string | null;
  /**
   * Zdefiniuj pola, które będą miały wpisy tej kolekcji (nazwa, typ, opcjonalnie opcje dla select).
   */
  fields: {
    /**
     * Nazwa techniczna bez spacji (np. price, productName).
     */
    key: string;
    /**
     * Czytelna nazwa w formularzu (np. "Cena", "Nazwa produktu").
     */
    label: string;
    type: 'text' | 'textarea' | 'number' | 'date' | 'checkbox' | 'select';
    required?: boolean | null;
    /**
     * Jedna opcja w każdej linii (tylko dla typu Select).
     */
    options?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Wpisy do własnych kolekcji. Wybierz definicję kolekcji (np. Cennik), następnie wypełnij pola w sekcji "Dane" zgodnie z definicją.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-collection-entries".
 */
export interface CustomCollectionEntry {
  id: number;
  /**
   * Nazwa systemowa w CMS (np. "cennik 1 szkic").
   */
  systemName: string;
  /**
   * Wybierz definicję kolekcji (np. Cennik). Pola w "Dane" zależą od tej definicji.
   */
  customCollection: number | CustomCollectionDefinition;
  /**
   * Sortowanie (mniejsza wartość = wyżej).
   */
  sortOrder?: number | null;
  /**
   * Wartości pól zdefiniowanych w wybranej kolekcji. Klucze muszą odpowiadać "Kluczowi pola" z definicji (np. {"productName": "Usługa A", "price": 100}).
   */
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq-categories';
        value: number | FaqCategory;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'custom-collection-definitions';
        value: number | CustomCollectionDefinition;
      } | null)
    | ({
        relationTo: 'custom-collection-entries';
        value: number | CustomCollectionEntry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  featuredImage?: T;
  publishedAt?: T;
  readTimeMinutes?: T;
  categories?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageType?: T;
  slug?: T;
  title?: T;
  shortDescription?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  sortOrder?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  logo?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-collection-definitions_select".
 */
export interface CustomCollectionDefinitionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  useAsTitle?: T;
  fields?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        required?: T;
        options?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-collection-entries_select".
 */
export interface CustomCollectionEntriesSelect<T extends boolean = true> {
  customCollection?: T;
  sortOrder?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top-level tabs (e.g. Platform, Integrations, Resources). Order determines display order.
   */
  tabs?:
    | {
        label: string;
        menuItems?:
          | {
              label: string;
              /**
               * Link target (e.g. /page or https://...)
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  contactEmail: string;
  contactPhone: string;
  /**
   * Footer link columns (e.g. Registration, Sign in, Search, Privacy policy, Terms, FAQ).
   */
  linkColumns?:
    | {
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Mapowanie typów stron (pageType) na kolekcje Payload. Każdy wpis definiuje, skąd pobierać dane dla strony o danym typie. Dodaj nowy wpis, aby dodać własny typ strony (np. testimonials).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-type-collections".
 */
export interface PageTypeCollection {
  id: number;
  /**
   * Dodaj wpis dla każdego typu strony, który ma ładować dane z kolekcji. W kolekcji Pages ustaw pageType na wartość "Page type key" z tego wpisu.
   */
  entries?:
    | {
        /**
         * Unikalny identyfikator (np. faq, integrations, news, testimonials). Ta wartość wybierana jest w dokumencie strony (Pages) w polu Page type.
         */
        pageType: string;
        /**
         * Czytelna nazwa w panelu (np. FAQ, Integrations, News).
         */
        label: string;
        /**
         * Kolekcja Payload, z której pobierane są dokumenty jako dane strony.
         */
        collection: 'faq-categories' | 'integrations' | 'posts' | 'categories' | 'custom-collection-entries';
        /**
         * Pole sortowania (np. sortOrder, -publishedAt, name). Minus = malejąco.
         */
        sort: string;
        /**
         * Maksymalna liczba dokumentów do pobrania.
         */
        limit: number;
        /**
         * Głębokość zagnieżdżeń (relacje). Zazwyczaj 1.
         */
        depth: number;
        /**
         * Wymagane, gdy Collection = "Custom (własna kolekcja)". Wybierz wcześniej utworzoną definicję (np. Cennik).
         */
        customCollectionDefinition?: (number | null) | CustomCollectionDefinition;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        label?: T;
        menuItems?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactEmail?: T;
  contactPhone?: T;
  linkColumns?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-type-collections_select".
 */
export interface PageTypeCollectionsSelect<T extends boolean = true> {
  entries?:
    | T
    | {
        pageType?: T;
        label?: T;
        collection?: T;
        sort?: T;
        limit?: T;
        depth?: T;
        customCollectionDefinition?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}